### ISSUE TITLE
about open source

### ISSUE THREAD

**Issue by ares89** [OpenDriveLab/HDGT#1]
hi, @jiaxiaosong1002 

This work is great! Will the code be released? Or this repository is only for the website?

Thanks~

**Comment by jiaxiaosong1002** [comment]
Thank you for your interests. Yes, we will release it upon the acceptance of the paper.

**Comment by kargarisaac** [comment]
Thank you for the great work. Do you have an estimate of the time? I'm gonna start my next phd paper based on this amazing work. Is it possible to get the code in private?

**Comment by jiaxiaosong1002** [comment]
> Thank you for the great work. Do you have an estimate of the time? I'm gonna start my next phd paper based on this amazing work. Is it possible to get the code in private?

Thank you for your interests.  Please understand that it is hard for us to esitimate the time of reviewing process. We will release the code as soon as possible once get accepted.
