### ISSUE TITLE
Module found error "metricss_soft_map"

### ISSUE THREAD

**Issue by Tangchengchen** [OpenDriveLab/HDGT#9]
Traceback (most recent call last):
  File "train.py", line 23, in <module>
    from metricss_soft_map import soft_map
ModuleNotFoundError: No module named 'metricss_soft_map'

How to install the module named "metricss_soft_map", I cannot install it with pip and conda, could I  delete the module since I found no referene of this module in code?

**Comment by jiaxiaosong1002** [comment]
Hi @512197,

Yes. You could simply delete it. It is uncleaned old code.

Thanks for your reminder!

**Comment by Tangchengchen** [comment]
@jiaxiaosong1002  

ok, thanks for your reply!
